load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

rules_pkg_version="2ad5bd8fa4dc034081c616521bc7d6a45eb21818"

http_archive(
  name = "rules_pkg",
  strip_prefix= "rules_pkg-%s/pkg" % rules_pkg_version,
  urls = ["https://github.com/bazelbuild/rules_pkg/archive/%s.tar.gz" % rules_pkg_version],
)

load("@rules_pkg//:deps.bzl", "rules_pkg_dependencies")
rules_pkg_dependencies()

# custom version
rules_docker_version = "1fb7602779ee289ed67eb221d9f9a63d127f940b"

http_archive(
  name = "io_bazel_rules_docker",
  strip_prefix= "rules_docker-%s" % rules_docker_version,
  urls = ["https://github.com/bazelbuild/rules_docker/archive/%s.tar.gz" % rules_docker_version],
  sha256 = "38f6cf83ebb94e543a7a4ad05ff55b8ab3359ca92b64f499fb257579842c39d2",
)

load(
    "@io_bazel_rules_docker//repositories:repositories.bzl",
    container_repositories = "repositories",
)

container_repositories()

load("@io_bazel_rules_docker//repositories:deps.bzl", container_deps = "deps")

container_deps()

load("//:external_docker_images.bzl", "external_images")

external_images()

http_archive(
  name = "nodejs_distro_12",
  urls = ["https://nodejs.org/dist/v12.18.3/node-v12.18.3-linux-x64.tar.gz"],
  sha256 = "8cdacecc43c35bcfa5474c793b9e7a01835e4171264f7b13f3e57093371872e9",
  strip_prefix="node-v12.18.3-linux-x64",
  build_file_content = """package(default_visibility = ["//visibility:public"])
load("@rules_pkg//:pkg.bzl", "pkg_tar")
_external_name = repository_name()[1:]
filegroup(
  name = _external_name + "_files",
  srcs = glob(include = ["**/**"], exclude=["BUILD.bazel","WORKSPACE"]),
)

pkg_tar(
  name = _external_name,
  package_dir = "/usr/local/lib/nodejs/current",
  srcs = ["nodejs_distro_12_files"],
  strip_prefix = "/external/" + _external_name,
  symlinks = {
    "/usr/local/lib/nodejs/current/bin/npm": "../lib/node_modules/npm/bin/npm-cli.js",
    "/usr/local/lib/nodejs/current/bin/npx": "../lib/node_modules/npm/bin/npx-cli.js",
    "/usr/local/bin/node" : "/usr/local/lib/nodejs/current/bin/node",
    "/usr/local/bin/npm" : "/usr/local/lib/nodejs/current/bin/node",
    "/usr/local/bin/npx" : "/usr/local/lib/nodejs/current/bin/npx",
  }
)
"""
)